---
title: "MH4510 Project Test"
author: "Chin Ao-Wen"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
install.packages("reticulate")
install.packages("MLmetrics")
```

```{r}
library(reticulate)
library(caret)
library(dplyr)
library(xgboost)
library(MLmetrics)

set.seed(42)
```


```{r}
np = import("numpy")
```

```{r}
## READ DATA ## 
# Original hyperparams
train_data = read.csv("datasets/classical_train.csv")
val_data = read.csv("datasets/classical_val.csv")

# Using new hyperparams
train_data = read.csv("datasets_new_params/classical_train.csv")
val_data = read.csv("datasets_new_params/classical_val.csv")
#test_data = read.csv("datasets_new_params/classical_test.csv")
```

```{r}
##### ========== PRE-PROCESSING ========== #####

# Scale data
preproc = preProcess(train_data[, -ncol(train_data)], method = c("center", "scale")) # standardize using train set
train_scaled = predict(preproc, train_data)
val_scaled  = predict(preproc, val_data) # apply the scaling params used to the val data

# Convert labels to factors
train_data$Emotion = as.factor(train_data$Emotion)
val_data$Emotion = as.factor(val_data$Emotion)

str(train_data)
```

```{r}
# Subset selected columns/features only 
train_data_subset = train_data[, c(1:30, ncol(train_data))]
val_data_subset = val_data[, c(1:30, ncol(val_data))]
```


```{r}
##### ========== LOG MODEL ========== #####

ctrl = trainControl(method='cv', number=5)

log_model = train(
  Emotion ~ .,
  data = train_data_subset,
  method = "multinom",
  trControl = ctrl,
  trace = FALSE
)
```

```{r}
log_model
```

```{r}
##### ========== RANDOM FOREST MODEL ========== #####
ctrl = trainControl(method='cv', number=5)
rf_model = train(
  Emotion ~., 
  data = train_data_subset,
  method = "rf",
  trControl = ctrl,
  tuneLength = 5
)

rf_model
```

```{r}
# Make predictions
pred = predict(rf_model, newdata = val_data_subset)

# Confusion matrix
conf_mat = confusionMatrix(pred, val_data$Emotion)
print(conf_mat)

```

```{r}
##### ========== TUNING RANDOM FOREST MODEL ========== #####
ctrl = trainControl(
  method = "cv",
  number = 5,
  verboseIter = TRUE    # shows progress
)

# Define grid of parameters to search over
rf_grid = expand.grid(
    mtry = c(1:10),
    splitrule = "gini",
    min.node.size = 1
  )

rf_model_ranger = train(
  Emotion ~ .,
  data = train_data_subset,
  method = "ranger",
  trControl = ctrl,
  tuneGrid = rf_grid,
  num.trees = 500
)

pred <- predict(rf_model_ranger, newdata = val_data_subset)
conf_mat <- confusionMatrix(pred, val_data$Emotion)
print(conf_mat)

```
```{r}
rf_model_ranger$bestTune
```



```{r}
##### ========== XG-BOOST MODEL ========== #####
xgb_grid = expand.grid(
  nrounds = c(100, 300, 500),        # number of boosting iterations
  max_depth = c(3, 6, 9),            # depth of each tree
  eta = c(0.01, 0.05, 0.1),          # learning rate
  gamma = c(0, 0.1, 0.5),            # minimum loss reduction
  colsample_bytree = c(0.7, 0.8),    # subsample ratio of columns
  min_child_weight = c(1, 5, 10),    # min sum of instance weight
  subsample = c(0.7, 0.8)            # subsample ratio of training instances
)

# Set training control
ctrl = trainControl(
  method = "cv",
  number = 5,               # 5-fold CV
  verboseIter = TRUE,
  classProbs = TRUE,
  summaryFunction = multiClassSummary # for multi-class emotion classification
)
```


```{r}
y = factor(make.names(train_data[, ncol(train_data)]))

xgb_model = train(
  x = train_data[, -ncol(train_data)],       # your MFCC feature matrix
  y = y,        # your labels (emotions)
  method = "xgbTree",
  trControl = ctrl,
  tuneLength = 5,
  metric = "Accuracy" # or "Kappa" if you want a balanced metric
)

print(xgb_model)
plot(xgb_model)
```

```{r}
print(max(xgb_model$results$Accuracy))
```


